import React from 'react'
import Head from 'next/head'
import Image from 'next/image'

const login = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css' />

            </Head>
            <div className="container" id="container">
                <div className="form-container sign-up-container mt-4">
                    <form action="#">
                        <Image
                            src="/image/logo1.png"
                            alt="r"
                            width={50}
                            height={50}
                        />
                        <h2>Create an account</h2>
                        <div className="social-container">
                            <a href="#" className="social"><i className="fab fa-facebook-f"></i></a>
                            <a href="#" className="social"><i className="fab fa-google-plus-g"></i></a>
                            <a href="#" className="social"><i className="fab fa-linkedin-in"></i></a>
                        </div>
                        <span>or use your email for registration</span>
                        <input type="text" placeholder="Username" />
                        <input type="email" placeholder="Email Address" />
                        <input type="password" placeholder="Password" />
                        <input type="password" placeholder="Confirm Password" />
                        <button className='rounded-pill'>Sign Up</button>
                    </form>
                </div>
                <div className="form-container sign-in-container">
                    <form action="#">
                        <Image
                            src="/image/logo1.png"
                            alt="r"
                            width={50}
                            height={50}
                        />
                        <h1>Sign in</h1>
                        <div className="social-container">
                            <a href="#" className="social"><i className="fab fa-facebook-f"></i></a>
                            <a href="#" className="social"><i className="fab fa-google-plus-g"></i></a>
                            <a href="#" className="social"><i className="fab fa-linkedin-in"></i></a>
                        </div>
                        <span>or use your account</span>
                        <input className="mt-2" type="email" placeholder="Username" />
                        <input className="mt-2" type="password" placeholder="Password" />
                        <a className="text-secondary" href="#">Forgot your password?</a>
                        <button className='rounded-pill'>Sign In</button>
                    </form>
                </div>
                <div className="overlay-container">
                    <div className="overlay">
                        <div className="overlay-panel overlay-left">
                            <Image
                                src="/image/icon-white.png"
                                alt="r"
                                width={50}
                                height={50}
                            />
                            <button className="ghost rounded-pill" id="signIn">Sign In</button>
                        </div>
                        <div className="overlay-panel overlay-right">
                        <Image
                                src="/image/icon-white.png"
                                alt="r"
                                width={200}
                                height={200}
                            />
                            <p>Manage your grocery easy with us</p>
                            <button className="ghost rounded-pill" id="signUp">Sign Up</button>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default login